import React from 'react';
import Dropdown from '../../components/DropDown/DropDown';
import styles from "./about.module.css";

const About = () => {
    return (
        <div className={styles.about}>
            <h1 className={styles.h1}>About us / FAQ</h1>
            <Dropdown title="What is this site?">
                <p className={styles.dropped}>
                    This tool was designed and created by 5 University 
                    of Ottawa students for Rutgers University. 
                    This tool aims to provide professors with specialized help to make
                    their courses more accessible. Whether it's a CSV file or a simple question, this tool can help!
                </p>
            </Dropdown>
            <Dropdown title="Is my data safe?">
                <p className={styles.dropped}>
                    As this tool uses OpenAI services, 
                    the data will be sent to their facilities.
                    In turn, this makes the service non-private, 
                    so make sure not to send any sensitive information.
                    The CSV files generated by Ally do not contain any 
                    information besides image names.
                </p>
            </Dropdown>
            <Dropdown title="What kind of questions can I ask?">
                <p className={styles.dropped}>
                    This chatbot will only answer questions related to course content,
                    how to navigate to make changes, and how to make the course more accessible.
                    It will not be able to answer any personal questions or questions that are not
                    related to the course.
                </p>
            </Dropdown>
            <Dropdown title="Contact Us">
                <p className={styles.dropped}>
                    If you have any questions or concerns, 
                    feel free to contact us at:
                    <a href="mailto:gng2101@gmail.com"> gng2101@gmail.com</a>
                </p>
            </Dropdown>
        </div>
    );
};

export default About;
